#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#./nvidia-settings-rc
xrandr --output DP-2 --mode 5120x1440 --rate 240
#fe --bg-scale /home/wragdan/.config/bg4.jpg
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
xset -dpms
xset s noblank
xset s on
xset s 180 120
#xss-lock -- slock -m "$(cowsay "Your screen is locked")" &

#autostart="mpd xcompmgr dunst unclutter pipewire remapd"
autostart="picom dunst pipewire"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
