shadow = false;
fading = false;
blur-background = false;
corner-radius = 0; # You can disable rounded corners too if you like.

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

opacity-rule = [
];

# 4. Optional: Backend selection (xrender is the default and simplest)
backend = "xrender";
