theme = "catppuccin_mocha"

[editor]
line-number = "relative"
true-color = true
mouse = false

#[editor.file-picker]
#file-explorer-mode = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
enable = true
display-messages = true


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-6 = ":buffer-previous"

[keys.normal."backspace"]
s = [":w", ":config-reload"]
c = [":config-open"]

[keys.normal."space"]
f = "file_picker_in_current_buffer_directory"
