return {
	cmd = { "biome", "lsp-proxy" },
	workspace_required = true,
	root_markers = {
		"package.json",
		".git",
		"package-lock.json",
		"yarn.lock",
		"pnpm-lock.yaml",
		"bun.lockb",
		"bun.lock",
		"biome.json",
		"biome.jsonc",
	},
	filetypes = {
		"astro",
		"css",
		"graphql",
		"html",
		"javascript",
		"javascriptreact",
		"json",
		"jsonc",
		"svelte",
		"typescript",
		"typescriptreact",
		"vue",
	},
}
